{% set name = "redshift-connector" %}
{% set version = "2.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/amazon-redshift-python-driver/archive/v{{ version }}.tar.gz
  sha256: 107623a7e27a058976c426eeb3fbc77e764f9e7858323385f4034f654c31a66b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36]

requirements:
  host:
    - python
    - wheel
    - setuptools
    - pip
  run:
    - python
    - scramp >=1.2.0,<1.5.0
    - pytz >=2020.1
    - beautifulsoup4 >=4.7.0,<5.0.0
    - boto3 >=1.9.201,<2.0.0
    - requests >=2.23.0,<3.0.0
    - lxml >=4.6.5
    - botocore >=1.12.201,<2.0.0
    - packaging

test:
  source_files:
    - test
  imports:
    - redshift_connector
  commands:
    - pip check
    - pytest -v test/unit
  requires:
    - pip
    - pytest >=5.4.0,<7.4.0
    - pytest-mock >=1.11.1,<=3.2.0

about:
  home: https://github.com/aws/amazon-redshift-python-driver
  summary: Redshift interface library
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  description: |
    redshift_connector is the Amazon Redshift connector for Python. 
    Easy integration with pandas and numpy, 
    as well as support for numerous Amazon Redshift specific features help you get the most out of your data
    Supported Amazon Redshift features include:
      IAM authentication
      Identity provider (IdP) authentication
      Redshift specific data types
    This pure Python connector implements Python Database API Specification 2.0.
  dev_url: https://github.com/aws/amazon-redshift-python-driver
  doc_url: https://github.com/aws/amazon-redshift-python-driver/blob/master/README.rst

extra:
  recipe-maintainers:
    - snegireff
